### PR TITLE
More v1.4 Bug Fixes

### LINKED ISSUE #169: [PE-D] Single word commands
All single word commands (e.g. list, help etc.) work even when there's extra stuff at the back (like "help 12345678" still works).

Not sure if you would consider this a bug?

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: EthanWong6362/ped#4

### LINKED ISSUE #172: [PE-D] Odd name validity
the app currently allows me to parse " 7 " with the two spaces at either side which doesn't seem like a name

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: hpkoh/ped#2

### LINKED ISSUE #185: [PE-D] list command works with additional keywords
The above command works when it should not, I think it should be handled as an invalid command.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: limzk126/ped#7

### LINKED ISSUE #186: [PE-D] Repeated names not allowed
Not sure if this is intended behaviour but I cannot add another person with the same name if a contact with that name already appears in Cohort Connect:

I think this could lead to problems if the user wishes to add people who have the same name but are different people.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: okyntary/ped#6

### LINKED ISSUE #187: [PE-D] Invalid files for import
Something like "import doesntexist.csv" doesn't allow you to hit enter. Works fine with json files though.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: EthanWong6362/ped#8

### LINKED ISSUE #188: [PE-D] show ambiguity
since numbers can be used for names. When I key in show 2, the data of the person at index is shown. However this can be confusing as I can name a person 2 as well

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: hpkoh/ped#4

### LINKED ISSUE #189: [PE-D] Show 0 being weird(?
Show 0 gives a "no user with this name" error instead of a "invalid index" error.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: EthanWong6362/ped#9

### LINKED ISSUE #192: [PE-D] Editing contacts to have same details
I can edit contacts so that they have exactly the same details (name, Telegram, Github):

I don't think this is intended behaviour.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: okyntary/ped#8

### LINKED ISSUE #194: [PE-D] show functionality does not work as specified by the UG
UG mentioned that the find command will show the contact you want if the name is the exact same.

I typed in 'find ADam Oh', it does not show the correct contact.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: limzk126/ped#9

### LINKED ISSUE #202: [PE-D] Command 'te' works with additional parameters. It should be handled
Typing the command 'te ammates' works despite being an incorrect command.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: limzk126/ped#14

### LINKED ISSUE #203: [PE-D] Command 'g' works with additional parameters.
Typing the command 'g edamame Oh' works despite it being an incorrect command.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: limzk126/ped#15

### LINKED ISSUE #211: [PE-D] Help Window does not appear if already minimized
Small issue, but I'm expecting the help window to always pop up whenever I press F1, or when I select it from the menu.

If it was already open but minimized, neither of those previous options will bring it up, as it (I assume) already sees that it's open.

I'm basing this assumption on my experience with old Microsoft products (Word, Excel) etc.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: okyntary/ped#5

### PR DESCRIPTION
**Pull request by crypto-code**
- [x] Resolve #211, by bringing to front.
- [x] Resolve #192, by keeping GitHub and Telegram  unique.
- [x] Resolve #189, by giving specific error messages.
- [x] Resolve #188, by not allowing numbers in names.
- [x] Resolve #172,  by not allowing numbers in names.
- [x] Resolve #194
- [x] Add Show by telegram and github also.
- [x] Resolve #186, by keeping telegram and github as unique only.
- [x] Resolve #187, by handling errors in case of non-existent csv file.
- [x] Resolve #185, by adding checks for single word commands
- [x] Resolve #169, by adding checks for single word commands
- [x] Resolve #203, by adding checks for single word commands
- [x] Resolve #202, by adding checks for single word commands

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ShowCommandParser.java [hunk 1]
```diff
@@ -24,23 +28,53 @@
...
+
+        Integer ind = StringUtil.getInt(argMain);
+        if (ind != null && ind <= 0) {
+            throw new ParseException(ShowCommand.MESSAGE_INVALID_INDEX);
+        }
+
+
+        if (!Name.isValidName(argMain)) {
+            throw new ParseException(ShowCommand.MESSAGE_INVALID_NAME);
+        }
```
Comment (CheongYeeMing) [inline src/main/java/seedu/address/logic/parser/ShowCommandParser.java:75]: Good use of defensive programming! 👍

**Review by CheongYeeMing — APPROVED** [review]
Well written code! Test cases updated when resolving issues from PE-D. 😄

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 2]
```diff
@@ -70,6 +70,23 @@ public static boolean isNonZeroUnsignedInteger(String s) {
         }
     }
 
+    /**
+     * Returns Integer if {@code s} represents an unsigned integer
+     * e.g. 0, 1, 2, 3, ..., {@code Integer.MAX_VALUE} <br>
+     * Will return null for any other non-null string input
+     * e.g. empty string, "-1", "+1", and " 2 " (untrimmed), "3 0" (contains whitespace), "1 a" (contains letters)
+     * @throws NullPointerException if {@code s} is null.
+     */
```
Comment (CheongYeeMing) [inline src/main/java/seedu/address/commons/util/StringUtil.java:79]: Hi, do leave an empty line between the description and the `@throws` as part of our standardisation of Javadocs format. 😄

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 3]
```diff
@@ -70,6 +70,23 @@ public static boolean isNonZeroUnsignedInteger(String s) {
...
+        try {
+            return Integer.parseInt(s); // "+1" is successfully parsed by Integer#parseInt(String)
+        } catch (NumberFormatException nfe) {
+            return null;
+        }
+    }
+
     public static String clean(String s) {
         return s.strip().replaceAll("[\n|\r|\"|\f|\b|']", "").replaceAll("\\s+", " ").strip();
     }
```
Comment (CheongYeeMing) [inline src/main/java/seedu/address/commons/util/StringUtil.java:92]: It will be better to set `\\s+` as a variable as it is repeated a few times. (Take a look at `containsWordIgnoreCase` method above).

File: src/main/java/seedu/address/logic/commands/ShowCommand.java [hunk 4]
```diff
@@ -28,23 +28,29 @@
...
+    public static final String MESSAGE_INVALID_INDEX = "The Index must be A Non-Zero Positive Integer.";
+
+    public static final String MESSAGE_INVALID_NAME = "The Name is Invalid.";
 
     public static final String MESSAGE_SUCCESS = "Showing details for %1$s.";
 
-    public static final String MESSAGE_MULTIPLE_NAME = "%1$d Persons with the given keyword in their name exists.\n"
-            + "You can try show with index or full name";
+    public static final String MESSAGE_MULTIPLE_NAME = "%1$d Persons with the given keyword in their %2$s exists.\n"
+            + "You can try show with index or full %2$s";
```
Comment (CheongYeeMing) [inline src/main/java/seedu/address/logic/commands/ShowCommand.java:40]: Good use of variables! 👍

File: src/main/java/seedu/address/model/person/Person.java [hunk 5]
```diff
@@ -225,13 +220,8 @@ public boolean equals(Object other) {
...
         Person otherPerson = (Person) other;
-        return otherPerson.getName().equals(getName())
-                && otherPerson.getTelegram().equals(getTelegram())
-                && otherPerson.getGithub().equals(getGithub())
-                && otherPerson.getPhone().equals(getPhone())
-                && otherPerson.getEmail().equals(getEmail())
-                && otherPerson.getAddress().equals(getAddress())
-                && otherPerson.getTags().equals(getTags());
+        return otherPerson.getTelegram().equals(getTelegram())
+                || otherPerson.getGithub().equals(getGithub());
```
Comment (CheongYeeMing) [inline src/main/java/seedu/address/model/person/Person.java:224]: Resolves the issue for "duplicate" contacts! 👍

File: src/main/java/seedu/address/model/tag/Tag.java [hunk 6]
```diff
@@ -49,6 +49,11 @@ public boolean isEvent() {
         return type == Type.EVENT;
     }
 
+    public String getStringType() {
+        String[] types = new String[] {"", "event-", "mod-"};
+        return types[type.ordinal()];
```
Comment (CheongYeeMing) [inline src/main/java/seedu/address/model/tag/Tag.java:54]: Similar issue. `"event-"` and `"mod-"` repeated below in `parseTagType`. Better to set as variables. 😄

**Review by CheongYeeMing — APPROVED** [review]
Many issues were resolved. Just some minor changes to be done! 👍

File: src/main/java/seedu/address/logic/commands/ShowCommand.java [hunk 7]
```diff
@@ -55,27 +61,28 @@ public ShowCommand(Predicate<Person> predicate) {
...
 
     /**
      * Executes the show command if argument is a string name
      */
-    private CommandResult executeWithName(Model model) throws CommandException {
+    private CommandResult executeWithOthers(Model model) throws CommandException {
         FilteredList<Person> filteredList = new FilteredList<>(model.getFilteredPersonList());
         filteredList.setPredicate(predicate);
 
         if (filteredList.isEmpty()) {
```
Comment (moreTriangles) [inline src/main/java/seedu/address/logic/commands/ShowCommand.java:75]: Deep nesting, arrowhead style code. Possible to abstract further?

File: src/main/java/seedu/address/logic/commands/ShowCommand.java [hunk 8]
```diff
@@ -55,27 +61,28 @@ public ShowCommand(Predicate<Person> predicate) {
...
             filteredList = new FilteredList<>(model.getAddressBook().getPersonList());
             filteredList.setPredicate(predicate);
             if (filteredList.isEmpty()) {
-                throw new CommandException(MESSAGE_NO_NAME);
+                throw new CommandException(String.format(MESSAGE_NO_TARGET, searchBy));
             } else {
```
Comment (moreTriangles) [inline src/main/java/seedu/address/logic/commands/ShowCommand.java:80]: `else` here can be omitted to reduce nesting

File: src/main/java/seedu/address/logic/parser/AddressBookParser.java [hunk 9]
```diff
@@ -56,6 +56,32 @@ public Command parseCommand(String userInput) throws ParseException {
         logger.info("----------------[COMMAND WORD][" + commandWord + "]");
         final String arguments = matcher.group("arguments");
         logger.info("----------------[ARGUMENTS][" + arguments + "]");
+
```
Comment (moreTriangles) [inline src/main/java/seedu/address/logic/parser/AddressBookParser.java:59]: Neat way to handle all single words commands

**Review by moreTriangles — CHANGES_REQUESTED** [review]
Great work, just minor formatting issues

**Review by moreTriangles — APPROVED** [review]
LGTM 👍
